name: pytest
on:
  push:
    branches:
      - main
    paths:
      - 'src/*'
      - 'config/*'
      - '.github/worflows/*'
  pull_request:
    branches:
        -main

jobs:
  unit-test:
    timeout-minutes: 10
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - uses: actions/checkout@v2
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest -s ./tests/
